---
repos:
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args:
          - --ignore=E501,E722
          - --line-length=88
          - --target-version=py311
          - --fix
  - repo: https://github.com/crate-ci/typos
    rev: v1.24.6
    hooks:
      - id: typos
        args:
          [
            --config=.typos.toml,
          ]
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.17.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-xml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          [
            --autofix,
            --indent=2,
            --no-sort-keys,
          ]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
